/* Shop.js */

// Wait until shop.html has finished loading, once that has happened run the function below. 
// Once function runs it calls fetchListingsFromMongoDB
window.addEventListener("load", function() {
  console.log("Running!!!!!!!!!!!!!!!!");
  fetchListingsFromMongoDB();
});

// Method which retreives all listings from MongoDB in json data format
async function fetchListingsFromMongoDB() {

  try {
    const res = await fetch('/fetch_all_listings', {
      method: 'GET'
  });
    const data = await res.json();

    // Log the data (Remove for deployment)
    console.log("This is all from the frontend")
    console.log(data);

    // Parse all data into showcaseListings
    showcaseListings(data.listings);
  } catch (err) {
    console.error("Fetch error:", err);
  }

}

// Method to showcase all listings on shop.js

function showcaseListings(listings) {
  const container = document.querySelector('.products-grid');
  let itemsHTML = '';

  const cloudinaryBase = 'https://res.cloudinary.com/dasqssuki/image/upload/';

 

  // for each listing, take its data and generate HTML
  listings.forEach(product => {

   
  

    // check whether stored listing has image url, if so display it, if not display default image
    const imgSrc = product.images?.[0]
      ? (product.images[0].startsWith('http') ? product.images[0] : cloudinaryBase + product.images[0])
      : 'images/placeholder.png';

      /* For now the class in itemsHTML: add_to_cart on click opens stripe, but later can add to actual button title buy now when data starts to get stroed in cart*/

    itemsHTML += `
      <div class="item-listing add_to_cart" data-id="${product._id}">
        <div class="item-listing-image" data-image="${imgSrc}">
          <img src="${imgSrc}" alt="${product.name}">
        </div>

        <div class="item-listing-description">
          <div class="item-description-details">
            <div class="item-listing-des-brand" data-brand="${product.brand}">${product.brand}</div>
            <div class="item-listing-des-name" data-name="${product.name}">${product.name}</div>
            <div class="item-listing-des-price" data-price="${product.price}">$${(product.price/100).toFixed(2)} USD</div>
            <div class="item-listing-des-size" data-size="${product.size}">Size: ${product.size || 'N/A'}</div>
            <div class="item-listing-des-gender" data-gender="${product.gender}">Gender: ${product.gender || 'N/A'}</div>
            <div class="item-listing-des-condition">Condition: ${product.condition || 'N/A'}</div>
            <div class="item-listing-des-stock" data-stock="${product.stock}">Stock: ${product.stock || 'N/A'}</div>
          </div>

          <div class="item-color-description">${product.color.join(', ')}</div>
        </div>
      </div>
    `;
  });

  container.innerHTML = itemsHTML;

  openListingFunctionality();
}

// Method which allows user to click on a listing which opens up a dynamic html page generated by the server (Product.html), showcasing all details for a listing as well as option to add to cart
function openListingFunctionality() {
  const itemListings = document.querySelectorAll('.item-listing');
  itemListings.forEach(item => {
    item.addEventListener("click", () => {

      // on click grab product id and then...
      const id = item.dataset.id;
      
      // Navigate to product.html and pass the ID via query string
      window.location.href = `product.html?id=${id}`;
    })
  })
}